<!--
@note Do Not Edit this file unless you understand what you are doing!
@author 侯志伟-houzhiwei
@date 2017-04
@email houzw@leris.ac.cn
-->
<template>
    <div v-if="show"  v-jspanel="jsPanelOptions">
      <slot></slot>
    </div>
</template>

<script>
// 自定义指令 jspanel
import jspanel from "jspanel4.js";

export default {
  name: "j-panel",
  data() {
    return {
      panelOptions: {
        contentSize: {
          width: 300,
          height: 300
        }
      }
    };
  },
  directives: {
    jspanel
  },
  computed:{
      jsPanelOptions(){
        return {
          panel:this.options,
          show:this.show
        }
      }
  },
  mounted() {
    this.$nextTick(() => {
      this.panelOptions = Object.assign({}, this.options);
    });
  },
  props: {
    options: {
      type: Object,
      required: true,
      default() {
        return {
            theme: "success",
            content: "<p>Panel Content here ...</p>"
        };
      }
    },
    show: {
      type: Boolean,
      required: true,
      default() {
        return false;
      }
    }
  }
};
</script>
<style lang="scss">
.jsPanel .jsPanel-content {
  font-size: inherit;
  border-top: unset !important;
}
</style>
