<!--
@note Do Not Edit this file unless you understand what you are doing!
@author 侯志伟-houzhiwei
@date 2017-04
@email houzw@leris.ac.cn
-->
<template>
    <div v-if="options.show"  v-jspanel="options">
      <slot></slot>
    </div>
</template>

<script>
  // 自定义指令 jspanel
  import jspanel from 'jspanel4.js'

  export default {
    name: 'j-panel',
    data() {
      return {
        panelOptions: {
          contentSize: {
            width: 300,
            height: 300
          }
        }// 控制显示大小等
      }
    },
    directives: {
      jspanel
    },
    mounted() {
      this.panelOptions = Object.assign({},this.options.panel);
    },
    props: {
      options: {
        type: Object,
        required: true,
        default () {
          return {
            show: false,
            // jsPanel options
            // http://jspanel.de/api/#option/overview
            panel: {
              theme: 'success',
              content: "<p>Panel Content here ...</p>",
            }
          }
        }
      }
    }
  }
</script>
<style lang="scss">
.jsPanel .jsPanel-content{
  font-size: inherit;
  border-top: unset !important;
}
</style>
